WARNING:fake_useragent:Error occurred during loading data. Trying to use cache server https://fake-useragent.herokuapp.com/browsers/0.1.8
Traceback (most recent call last):
  File "C:\Users\krish\AppData\Local\Programs\Python\Python36-32\lib\site-packages\fake_useragent\utils.py", line 166, in load
    verify_ssl=verify_ssl,
  File "C:\Users\krish\AppData\Local\Programs\Python\Python36-32\lib\site-packages\fake_useragent\utils.py", line 144, in get_browser_versions
    'No browsers version found for {browser}'.format(browser=browser))
fake_useragent.errors.FakeUserAgentError: No browsers version found for Edge/IE
ERROR:root:Except on auto_unfollow!
Traceback (most recent call last):
  File "C:\Users\krish\Downloads\instabot.py-master\instabot.py-master\src\instabot.py", line 848, in auto_unfollow
    user_info = all_data['user']
KeyError: 'user'
ERROR:root:Except on auto_unfollow!
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 848, in auto_unfollow
    user_info = all_data['user']
KeyError: 'user'
ERROR:root:Except on unfollow... Looks like a network error
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 652, in unfollow_on_cleanup
    time.sleep(300)
KeyboardInterrupt
ERROR:root:Except on auto_unfollow!
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 848, in auto_unfollow
    user_info = all_data['user']
KeyError: 'user'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:Except on auto_unfollow!
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 848, in auto_unfollow
    user_info = all_data['user']
KeyError: 'user'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:Except on auto_unfollow!
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 848, in auto_unfollow
    user_info = all_data['user']
KeyError: 'user'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 358, in get_media_id_by_tag
    self.media_by_tag = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])
KeyError: 'graphql'
ERROR:root:Except on unfollow... Looks like a network error
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 652, in unfollow_on_cleanup
    time.sleep(300)
KeyboardInterrupt
ERROR:root:Except on auto_unfollow!
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 848, in auto_unfollow
    user_info = all_data['user']
KeyError: 'user'
ERROR:root:Except on unfollow... Looks like a network error
Traceback (most recent call last):
  File "C:\Users\krish\AppData\Local\Programs\Python\Python36-32\lib\site-packages\urllib3\connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse(buffering=True)
TypeError: getresponse() got an unexpected keyword argument 'buffering'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 643, in unfollow_on_cleanup
    unfollow = self.s.post(url_unfollow)
  File "C:\Users\krish\AppData\Local\Programs\Python\Python36-32\lib\site-packages\requests\sessions.py", line 555, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "C:\Users\krish\AppData\Local\Programs\Python\Python36-32\lib\site-packages\requests\sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\krish\AppData\Local\Programs\Python\Python36-32\lib\site-packages\requests\sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\krish\AppData\Local\Programs\Python\Python36-32\lib\site-packages\requests\adapters.py", line 440, in send
    timeout=timeout
  File "C:\Users\krish\AppData\Local\Programs\Python\Python36-32\lib\site-packages\urllib3\connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "C:\Users\krish\AppData\Local\Programs\Python\Python36-32\lib\site-packages\urllib3\connectionpool.py", line 383, in _make_request
    httplib_response = conn.getresponse()
  File "C:\Users\krish\AppData\Local\Programs\Python\Python36-32\lib\http\client.py", line 1331, in getresponse
    response.begin()
  File "C:\Users\krish\AppData\Local\Programs\Python\Python36-32\lib\http\client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "C:\Users\krish\AppData\Local\Programs\Python\Python36-32\lib\http\client.py", line 258, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "C:\Users\krish\AppData\Local\Programs\Python\Python36-32\lib\socket.py", line 586, in readinto
    return self._sock.recv_into(b)
  File "C:\Users\krish\AppData\Local\Programs\Python\Python36-32\lib\ssl.py", line 1009, in recv_into
    return self.read(nbytes, buffer)
  File "C:\Users\krish\AppData\Local\Programs\Python\Python36-32\lib\ssl.py", line 871, in read
    return self._sslobj.read(len, buffer)
  File "C:\Users\krish\AppData\Local\Programs\Python\Python36-32\lib\ssl.py", line 631, in read
    v = self._sslobj.read(len, buffer)
KeyboardInterrupt
ERROR:root:Except on unfollow... Looks like a network error
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Desktop Folders\Lraja\Lraja\src\instabot.py", line 652, in unfollow_on_cleanup
    time.sleep(300)
KeyboardInterrupt
